# Generated by Django 5.1.1 on 2024-09-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_no', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('electrical_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_consumption', models.FloatField()),
                ('power_consumption', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartbtech.smartdevice')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingIncharge',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartbtech.building')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartbtech.reading')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartbtech.smartdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartbtech.users')),
            ],
        ),
    ]
