# Generated by Django 5.1.1 on 2024-09-19 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbtech', '0004_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='energy_consumption',
            new_name='pres_energy_rdg',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='datetime',
            new_name='reading_from',
        ),
        migrations.AddField(
            model_name='reading',
            name='current_consumption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reading',
            name='kwh_used',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='prev_energy_rdg',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='reading_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='voltage_consumption',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
