# Generated by Django 5.1.3 on 2024-11-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbtech', '0008_alter_reading_energy_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='energy_consumption',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='runtime_seconds',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='watt_seconds',
        ),
    ]
